services:
  web:
    build: .
    image: ghcr.io/beckjim/employee-dialogue:latest
    ports:
      - "5000:5000"
    volumes:
      # - app-data:/app/instance
      - ./instance:/app/instance
    environment:
      - FLASK_APP=app
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - AZURE_AD_CLIENT_SECRET=${AZURE_AD_CLIENT_SECRET}
    restart: unless-stopped

volumes:
  app-data:
